name: Build and release

on:
  workflow_dispatch:

jobs:
  linux:
    name: Linux build
    runs-on: ubuntu-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static library
        run: make static

      - name: Build dynamic library
        run: make dynamic

      - name: Create tar.gz file
        run: |
          tar -czf releases/bb101-linux.tar.gz lib/

      - name: Create tar.bz2 file
        run: |
          tar -cjf releases/bb101-linux.tar.bz2 lib/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 5
          path: releases/*.*
      - name: Clean
        run: make clean

  mac:
    name: MacOs build
    runs-on: macos-latest
    permissions: write-all

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build static library
        run: make static

      - name: Build dynamic library
        run: make dynamic

      - name: Create tar.gz file
        run: |
          tar -czf releases/bb101-mac.tar.gz lib/

      - name: Create tar.bz2 file
        run: |
          tar -cjf releases/bb101-mac.tar.bz2 lib/

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          retention-days: 5
          path: releases/*.*
      - name: Clean
        run: make clean
  
  release:
    name: release
    permissions: write-all
    runs-on: ubuntu-latest
    needs: [linux, mac]

    steps:
      - name: Download artifact
        uses: actions/download-artifact@v4

      - name: Release
        uses: marvinpinto/action-automatic-releases@master
        with:
          repo_token: '${{ secrets.DEPLOY_KEY }}'
          automatic_release_tag: ${{ needs.build-data.outputs.version }}
          prerelease: false
          title: 'Release build - ${{ needs.build-data.outputs.version }} (${{ needs.build-data.outputs.build_date }})'
          files: |
            bb101-mac.tar.bz2
            bb101-mac.tar.gz
            bb101-linux.tar.bz2
            bb101-linux.tar.gz

